## Potential Customer Yield Calculation with Rule-Based Classification

 Gezinomi wants to create new level-based sales definitions by using some features of the sales it makes, create segments according to these new sales definitions and estimate how much new customers can bring to the company on average based on these segments.

In [1]:
import pandas as pd


#pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

Read the miuul_gezinomi.xlsx file and show general information about the data set.

In [5]:
df = pd.read_excel(r'gezinomi\miuul_gezinomi.xlsx')
print(df.head())
print(df.shape)
print(df.info())

   SaleId   SaleDate CheckInDate  Price     ConceptName SaleCityName  \
0  415122 2022-12-03  2022-12-03  79.30    Herşey Dahil      Antalya
1  415103 2022-12-03  2022-12-03  45.97  Yarım Pansiyon      Antalya
2  404034 2022-09-12  2022-09-13  77.84    Herşey Dahil      Antalya
3  415094 2022-12-03  2022-12-10 222.71  Yarım Pansiyon        İzmir
4  414951 2022-12-01  2022-12-03 140.48  Yarım Pansiyon        İzmir

     CInDay  SaleCheckInDayDiff Seasons
0  Saturday                   0     Low
1  Saturday                   0     Low
2   Tuesday                   1    High
3  Saturday                   7     Low
4  Saturday                   2     Low
(59164, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59164 entries, 0 to 59163
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SaleId              59164 non-null  int64
 1   SaleDate            59164 non-null  datetime64[ns]
 2   CheckInDate         59164 non-null  datetime64[ns]
 3   Price               59151 non-null  float64
 4   ConceptName         59164 non-null  object
 5   SaleCityName        59164 non-null  object
 6   CInDay              59164 non-null  object
 7   SaleCheckInDayDiff  59164 non-null  int64
 8   Seasons             59164 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(4)
memory usage: 4.1+ MB
None

In [8]:
#How many unique cities are there? What are their frequencies?

print(df["SaleCityName"].unique())
print(df["SaleCityName"].value_counts())

['Antalya' 'İzmir' 'Diğer' 'Aydın' 'Muğla' 'Girne']
SaleCityName
Antalya    31649
Muğla      10662
Aydın      10646
Diğer       3245
İzmir       2507
Girne        455
Name: count, dtype: int64

In [10]:
# How many unique Concepts are there?

print(df["ConceptName"].nunique())

3

In [11]:
#  How many sales were made from which Concept?
print(df["ConceptName"].value_counts())

ConceptName
Herşey Dahil      53186
Yarım Pansiyon     3559
Oda + Kahvaltı     2419
Name: count, dtype: int64

In [12]:
# How much was earned from sales in total by city?
df.groupby("SaleCityName").agg({"Price": "sum"})

                  Price
SaleCityName
Antalya      2041911.10
Aydın         573296.01
Diğer         154572.29
Girne          27065.03
Muğla         665842.21
İzmir         165934.83

In [13]:
# How much was earned according to concept types?
df.groupby("ConceptName").agg({"Price": "sum"})

                    Price
ConceptName
Herşey Dahil   3332910.77
Oda + Kahvaltı  121308.35
Yarım Pansiyon  174402.35

In [14]:
# What are the PRICE averages by city?
df.groupby("SaleCityName").agg({"Price":"mean"})

              Price
SaleCityName
Antalya       64.52
Aydın         53.86
Diğer         47.71
Girne         59.48
Muğla         62.46
İzmir         66.27

In [15]:
# What are the PRICE averages according to concepts?
df.groupby(by=['ConceptName']).agg({"Price": "mean"})

                Price
ConceptName
Herşey Dahil    62.67
Oda + Kahvaltı  50.25
Yarım Pansiyon  49.03

In [16]:
# What are the PRICE averages in the City-Concept breakdown?
df.groupby(by=["SaleCityName", 'ConceptName']).agg({"Price": "mean"})

                             Price
SaleCityName ConceptName
Antalya      Herşey Dahil    64.52
             Oda + Kahvaltı  63.50
             Yarım Pansiyon  67.19
Aydın        Herşey Dahil    54.00
             Oda + Kahvaltı  34.46
             Yarım Pansiyon  30.02
Diğer        Herşey Dahil    84.77
             Oda + Kahvaltı  37.60
             Yarım Pansiyon  42.11
Girne        Herşey Dahil    97.68
             Oda + Kahvaltı  39.78
             Yarım Pansiyon  53.25
Muğla        Herşey Dahil    63.02
             Oda + Kahvaltı  59.04
             Yarım Pansiyon  45.12
İzmir        Herşey Dahil    74.70
             Oda + Kahvaltı  41.32
             Yarım Pansiyon  59.61

In [18]:
# Convert the sales_checkin_day_diff variable into a new categorical variable called EB_Score.
bins = [-1, 7, 30, 90, df["SaleCheckInDayDiff"].max()]
labels = ["Last Minuters", "Potential Planners", "Planners", "Early Bookers"]

In [19]:
df["EB_Score"] = pd.cut(df["SaleCheckInDayDiff"], bins, labels=labels)
df.head(50).to_excel("eb_scorew.xlsx", index=False)
df

,SaleId,SaleDate,CheckInDate,Price,ConceptName,SaleCityName,CInDay,SaleCheckInDayDiff,Seasons,EB_Score
0,415122,2022-12-03,2022-12-03,79.30,Herşey Dahil,Antalya,Saturday,0,Low,Last Minuters
1,415103,2022-12-03,2022-12-03,45.97,Yarım Pansiyon,Antalya,Saturday,0,Low,Last Minuters
2,404034,2022-09-12,2022-09-13,77.84,Herşey Dahil,Antalya,Tuesday,1,High,Last Minuters
3,415094,2022-12-03,2022-12-10,222.71,Yarım Pansiyon,İzmir,Saturday,7,Low,Last Minuters
4,414951,2022-12-01,2022-12-03,140.48,Yarım Pansiyon,İzmir,Saturday,2,Low,Last Minuters
...,...,...,...,...,...,...,...,...,...,...
59159,51817,2016-01-05,2016-10-10,54.30,Herşey Dahil,Antalya,Monday,279,Low,Early Bookers
59160,51816,2016-01-05,2016-10-10,54.30,Herşey Dahil,Antalya,Monday,279,Low,Early Bookers
59161,51814,2016-01-05,2016-01-06,40.56,Herşey Dahil,Diğer,Wednesday,1,Low,Last Minuters
59162,51736,2016-01-04,2016-01-05,69.85,Yarım Pansiyon,Diğer,Tuesday,1,Low,Last Minuters
59163,51731,2016-01-04,2016-08-22,158.94,Herşey Dahil,Antalya,Monday,231,High,Early Bookers

In [22]:
# See wage averages and frequencies by City, Concept, [EB_Score, Season, CInday]
df.groupby(by = ["SaleCityName", "ConceptName", "EB_Score"]).agg({"Price":["mean", "count"]})

                                               Price
                                                mean  count
SaleCityName ConceptName    EB_Score
Antalya      Herşey Dahil   Last Minuters      62.75  14148
                            Potential Planners 64.90   8874
                            Planners           67.88   4490
                            Early Bookers      66.49   3281
             Oda + Kahvaltı Last Minuters      65.35    503
...                                              ...    ...
İzmir        Oda + Kahvaltı Early Bookers      66.93      3
             Yarım Pansiyon Last Minuters      57.79    636
                            Potential Planners 64.80    198
                            Planners           60.51     47
                            Early Bookers      65.91     14

[72 rows x 2 columns]

In [24]:
df.groupby(by = ["SaleCityName", "ConceptName", "Seasons"]).agg({"Price":["mean", "count"]})

                                     Price
                                      mean  count
SaleCityName ConceptName    Seasons
Antalya      Herşey Dahil   High     64.92  27126
                            Low      61.55   3667
             Oda + Kahvaltı High     66.27    303
                            Low      60.67    295
             Yarım Pansiyon High     73.26    118
                            Low      62.00    138
Aydın        Herşey Dahil   High     54.95  10103
                            Low      33.68    473
             Oda + Kahvaltı High     30.39     27
                            Low      44.45     11
             Yarım Pansiyon High     32.63     20
                            Low      25.27     11
Diğer        Herşey Dahil   High     83.79    364
                            Low      87.31    141
             Oda + Kahvaltı High     34.84    349
                            Low      39.96    408
             Yarım Pansiyon High     39.73    516
                            Low      42.95   1462
Girne        Herşey Dahil   High    103.94     55
                            Low      90.94     51
             Oda + Kahvaltı High     39.48     66
                            Low      40.04     73
             Yarım Pansiyon High     58.38    100
                            Low      48.58    110
Muğla        Herşey Dahil   High     63.38   9582
                            Low      48.30    237
             Oda + Kahvaltı High     61.26    592
                            Low      37.77     62
             Yarım Pansiyon High     45.82    177
                            Low      32.68     10
İzmir        Herşey Dahil   High     74.75   1234
                            Low      74.31    147
             Oda + Kahvaltı High     54.14     86
                            Low      33.56    142
             Yarım Pansiyon High     87.66    118
                            Low      55.35    777

In [26]:
df.groupby(by = ["SaleCityName", "ConceptName", "CInDay"]).agg({"Price":["mean", "count"]})

                                      Price
                                       mean count
SaleCityName ConceptName    CInDay
Antalya      Herşey Dahil   Friday    62.66  4136
                            Monday    63.26  6831
                            Saturday  64.42  4741
                            Sunday    65.85  3818
                            Thursday  62.89  3898
...                                     ...   ...
İzmir        Yarım Pansiyon Saturday  52.50   315
                            Sunday    98.93    68
                            Thursday  52.48    91
                            Tuesday   56.14    73
                            Wednesday 54.06    86

[126 rows x 2 columns]

In [27]:
# Sort the output of the City-Concept-Season breakdown according to PRICE.
agg_df = df.groupby(["SaleCityName", "ConceptName", "Seasons"]).agg({"Price": "mean"}).sort_values("Price", ascending=False)
agg_df.head(20)

                                     Price
SaleCityName ConceptName    Seasons
Girne        Herşey Dahil   High    103.94
                            Low      90.94
İzmir        Yarım Pansiyon High     87.66
Diğer        Herşey Dahil   Low      87.31
                            High     83.79
İzmir        Herşey Dahil   High     74.75
                            Low      74.31
Antalya      Yarım Pansiyon High     73.26
             Oda + Kahvaltı High     66.27
             Herşey Dahil   High     64.92
Muğla        Herşey Dahil   High     63.38
Antalya      Yarım Pansiyon Low      62.00
             Herşey Dahil   Low      61.55
Muğla        Oda + Kahvaltı High     61.26
Antalya      Oda + Kahvaltı Low      60.67
Girne        Yarım Pansiyon High     58.38
İzmir        Yarım Pansiyon Low      55.35
Aydın        Herşey Dahil   High     54.95
İzmir        Oda + Kahvaltı High     54.14
Girne        Yarım Pansiyon Low      48.58

In [28]:
# Convert the names in the index to variable names.
agg_df.reset_index(inplace=True)
agg_df

   SaleCityName     ConceptName Seasons  Price
0         Girne    Herşey Dahil    High 103.94
1         Girne    Herşey Dahil     Low  90.94
2         İzmir  Yarım Pansiyon    High  87.66
3         Diğer    Herşey Dahil     Low  87.31
4         Diğer    Herşey Dahil    High  83.79
5         İzmir    Herşey Dahil    High  74.75
6         İzmir    Herşey Dahil     Low  74.31
7       Antalya  Yarım Pansiyon    High  73.26
8       Antalya  Oda + Kahvaltı    High  66.27
9       Antalya    Herşey Dahil    High  64.92
10        Muğla    Herşey Dahil    High  63.38
11      Antalya  Yarım Pansiyon     Low  62.00
12      Antalya    Herşey Dahil     Low  61.55
13        Muğla  Oda + Kahvaltı    High  61.26
14      Antalya  Oda + Kahvaltı     Low  60.67
15        Girne  Yarım Pansiyon    High  58.38
16        İzmir  Yarım Pansiyon     Low  55.35
17        Aydın    Herşey Dahil    High  54.95
18        İzmir  Oda + Kahvaltı    High  54.14
19        Girne  Yarım Pansiyon     Low  48.58
20        Muğla    Herşey Dahil     Low  48.30
21        Muğla  Yarım Pansiyon    High  45.82
22        Aydın  Oda + Kahvaltı     Low  44.45
23        Diğer  Yarım Pansiyon     Low  42.95
24        Girne  Oda + Kahvaltı     Low  40.04
25        Diğer  Oda + Kahvaltı     Low  39.96
26        Diğer  Yarım Pansiyon    High  39.73
27        Girne  Oda + Kahvaltı    High  39.48
28        Muğla  Oda + Kahvaltı     Low  37.77
29        Diğer  Oda + Kahvaltı    High  34.84
30        Aydın    Herşey Dahil     Low  33.68
31        İzmir  Oda + Kahvaltı     Low  33.56
32        Muğla  Yarım Pansiyon     Low  32.68
33        Aydın  Yarım Pansiyon    High  32.63
34        Aydın  Oda + Kahvaltı    High  30.39
35        Aydın  Yarım Pansiyon     Low  25.27

In [29]:
# Define new level based sales and add them to the data set as a variable.
agg_df['sales_level_based'] = agg_df[["SaleCityName", "ConceptName", "Seasons"]].agg(lambda x: '_'.join(x).upper(), axis=1)
agg_df

   SaleCityName     ConceptName Seasons  Price            sales_level_based
0         Girne    Herşey Dahil    High 103.94      GIRNE_HERŞEY DAHIL_HIGH
1         Girne    Herşey Dahil     Low  90.94       GIRNE_HERŞEY DAHIL_LOW
2         İzmir  Yarım Pansiyon    High  87.66    İZMIR_YARIM PANSIYON_HIGH
3         Diğer    Herşey Dahil     Low  87.31       DIĞER_HERŞEY DAHIL_LOW
4         Diğer    Herşey Dahil    High  83.79      DIĞER_HERŞEY DAHIL_HIGH
5         İzmir    Herşey Dahil    High  74.75      İZMIR_HERŞEY DAHIL_HIGH
6         İzmir    Herşey Dahil     Low  74.31       İZMIR_HERŞEY DAHIL_LOW
7       Antalya  Yarım Pansiyon    High  73.26  ANTALYA_YARIM PANSIYON_HIGH
8       Antalya  Oda + Kahvaltı    High  66.27  ANTALYA_ODA + KAHVALTI_HIGH
9       Antalya    Herşey Dahil    High  64.92    ANTALYA_HERŞEY DAHIL_HIGH
10        Muğla    Herşey Dahil    High  63.38      MUĞLA_HERŞEY DAHIL_HIGH
11      Antalya  Yarım Pansiyon     Low  62.00   ANTALYA_YARIM PANSIYON_LOW
12      Antalya    Herşey Dahil     Low  61.55     ANTALYA_HERŞEY DAHIL_LOW
13        Muğla  Oda + Kahvaltı    High  61.26    MUĞLA_ODA + KAHVALTI_HIGH
14      Antalya  Oda + Kahvaltı     Low  60.67   ANTALYA_ODA + KAHVALTI_LOW
15        Girne  Yarım Pansiyon    High  58.38    GIRNE_YARIM PANSIYON_HIGH
16        İzmir  Yarım Pansiyon     Low  55.35     İZMIR_YARIM PANSIYON_LOW
17        Aydın    Herşey Dahil    High  54.95      AYDIN_HERŞEY DAHIL_HIGH
18        İzmir  Oda + Kahvaltı    High  54.14    İZMIR_ODA + KAHVALTI_HIGH
19        Girne  Yarım Pansiyon     Low  48.58     GIRNE_YARIM PANSIYON_LOW
20        Muğla    Herşey Dahil     Low  48.30       MUĞLA_HERŞEY DAHIL_LOW
21        Muğla  Yarım Pansiyon    High  45.82    MUĞLA_YARIM PANSIYON_HIGH
22        Aydın  Oda + Kahvaltı     Low  44.45     AYDIN_ODA + KAHVALTI_LOW
23        Diğer  Yarım Pansiyon     Low  42.95     DIĞER_YARIM PANSIYON_LOW
24        Girne  Oda + Kahvaltı     Low  40.04     GIRNE_ODA + KAHVALTI_LOW
25        Diğer  Oda + Kahvaltı     Low  39.96     DIĞER_ODA + KAHVALTI_LOW
26        Diğer  Yarım Pansiyon    High  39.73    DIĞER_YARIM PANSIYON_HIGH
27        Girne  Oda + Kahvaltı    High  39.48    GIRNE_ODA + KAHVALTI_HIGH
28        Muğla  Oda + Kahvaltı     Low  37.77     MUĞLA_ODA + KAHVALTI_LOW
29        Diğer  Oda + Kahvaltı    High  34.84    DIĞER_ODA + KAHVALTI_HIGH
30        Aydın    Herşey Dahil     Low  33.68       AYDIN_HERŞEY DAHIL_LOW
31        İzmir  Oda + Kahvaltı     Low  33.56     İZMIR_ODA + KAHVALTI_LOW
32        Muğla  Yarım Pansiyon     Low  32.68     MUĞLA_YARIM PANSIYON_LOW
33        Aydın  Yarım Pansiyon    High  32.63    AYDIN_YARIM PANSIYON_HIGH
34        Aydın  Oda + Kahvaltı    High  30.39    AYDIN_ODA + KAHVALTI_HIGH
35        Aydın  Yarım Pansiyon     Low  25.27     AYDIN_YARIM PANSIYON_LOW

In [30]:
# Divide the personas into segments.
agg_df["SEGMENT"] = pd.qcut(agg_df["Price"], 4, labels=["D", "C", "B", "A"])
agg_df

,SaleCityName,ConceptName,Seasons,Price,sales_level_based,SEGMENT
0,Girne,Herşey Dahil,High,103.94,GIRNE_HERŞEY DAHIL_HIGH,A
1,Girne,Herşey Dahil,Low,90.94,GIRNE_HERŞEY DAHIL_LOW,A
2,İzmir,Yarım Pansiyon,High,87.66,İZMIR_YARIM PANSIYON_HIGH,A
3,Diğer,Herşey Dahil,Low,87.31,DIĞER_HERŞEY DAHIL_LOW,A
4,Diğer,Herşey Dahil,High,83.79,DIĞER_HERŞEY DAHIL_HIGH,A
5,İzmir,Herşey Dahil,High,74.75,İZMIR_HERŞEY DAHIL_HIGH,A
6,İzmir,Herşey Dahil,Low,74.31,İZMIR_HERŞEY DAHIL_LOW,A
7,Antalya,Yarım Pansiyon,High,73.26,ANTALYA_YARIM PANSIYON_HIGH,A
8,Antalya,Oda + Kahvaltı,High,66.27,ANTALYA_ODA + KAHVALTI_HIGH,A
9,Antalya,Herşey Dahil,High,64.92,ANTALYA_HERŞEY DAHIL_HIGH,B
10,Muğla,Herşey Dahil,High,63.38,MUĞLA_HERŞEY DAHIL_HIGH,B
11,Antalya,Yarım Pansiyon,Low,62.00,ANTALYA_YARIM PANSIYON_LOW,B
12,Antalya,Herşey Dahil,Low,61.55,ANTALYA_HERŞEY DAHIL_LOW,B
13,Muğla,Oda + Kahvaltı,High,61.26,MUĞLA_ODA + KAHVALTI_HIGH,B
14,Antalya,Oda + Kahvaltı,Low,60.67,ANTALYA_ODA + KAHVALTI_LOW,B
15,Girne,Yarım Pansiyon,High,58.38,GIRNE_YARIM PANSIYON_HIGH,B
16,İzmir,Yarım Pansiyon,Low,55.35,İZMIR_YARIM PANSIYON_LOW,B
17,Aydın,Herşey Dahil,High,54.95,AYDIN_HERŞEY DAHIL_HIGH,B
18,İzmir,Oda + Kahvaltı,High,54.14,İZMIR_ODA + KAHVALTI_HIGH,C
19,Girne,Yarım Pansiyon,Low,48.58,GIRNE_YARIM PANSIYON_LOW,C
20,Muğla,Herşey Dahil,Low,48.30,MUĞLA_HERŞEY DAHIL_LOW,C
21,Muğla,Yarım Pansiyon,High,45.82,MUĞLA_YARIM PANSIYON_HIGH,C
22,Aydın,Oda + Kahvaltı,Low,44.45,AYDIN_ODA + KAHVALTI_LOW,C
23,Diğer,Yarım Pansiyon,Low,42.95,DIĞER_YARIM PANSIYON_LOW,C
24,Girne,Oda + Kahvaltı,Low,40.04,GIRNE_ODA + KAHVALTI_LOW,C
25,Diğer,Oda + Kahvaltı,Low,39.96,DIĞER_ODA + KAHVALTI_LOW,C
26,Diğer,Yarım Pansiyon,High,39.73,DIĞER_YARIM PANSIYON_HIGH,C
27,Girne,Oda + Kahvaltı,High,39.48,GIRNE_ODA + KAHVALTI_HIGH,D
28,Muğla,Oda + Kahvaltı,Low,37.77,MUĞLA_ODA + KAHVALTI_LOW,D
29,Diğer,Oda + Kahvaltı,High,34.84,DIĞER_ODA + KAHVALTI_HIGH,D
30,Aydın,Herşey Dahil,Low,33.68,AYDIN_HERŞEY DAHIL_LOW,D
31,İzmir,Oda + Kahvaltı,Low,33.56,İZMIR_ODA + KAHVALTI_LOW,D
32,Muğla,Yarım Pansiyon,Low,32.68,MUĞLA_YARIM PANSIYON_LOW,D
33,Aydın,Yarım Pansiyon,High,32.63,AYDIN_YARIM PANSIYON_HIGH,D
34,Aydın,Oda + Kahvaltı,High,30.39,AYDIN_ODA + KAHVALTI_HIGH,D
35,Aydın,Yarım Pansiyon,Low,25.27,AYDIN_YARIM PANSIYON_LOW,D

In [32]:
agg_df.groupby("SEGMENT").agg({"Price": ["mean", "min","max", "sum"]})

        Price
         mean   min    max    sum
SEGMENT
D       33.37 25.27  39.48 300.30
C       44.89 39.73  54.14 403.99
B       60.27 54.95  64.92 542.47
A       82.47 66.27 103.94 742.21

In [33]:
#Sort the final df according to the price variable.
agg_df.sort_values(by="Price")

,SaleCityName,ConceptName,Seasons,Price,sales_level_based,SEGMENT
35,Aydın,Yarım Pansiyon,Low,25.27,AYDIN_YARIM PANSIYON_LOW,D
34,Aydın,Oda + Kahvaltı,High,30.39,AYDIN_ODA + KAHVALTI_HIGH,D
33,Aydın,Yarım Pansiyon,High,32.63,AYDIN_YARIM PANSIYON_HIGH,D
32,Muğla,Yarım Pansiyon,Low,32.68,MUĞLA_YARIM PANSIYON_LOW,D
31,İzmir,Oda + Kahvaltı,Low,33.56,İZMIR_ODA + KAHVALTI_LOW,D
30,Aydın,Herşey Dahil,Low,33.68,AYDIN_HERŞEY DAHIL_LOW,D
29,Diğer,Oda + Kahvaltı,High,34.84,DIĞER_ODA + KAHVALTI_HIGH,D
28,Muğla,Oda + Kahvaltı,Low,37.77,MUĞLA_ODA + KAHVALTI_LOW,D
27,Girne,Oda + Kahvaltı,High,39.48,GIRNE_ODA + KAHVALTI_HIGH,D
26,Diğer,Yarım Pansiyon,High,39.73,DIĞER_YARIM PANSIYON_HIGH,C
25,Diğer,Oda + Kahvaltı,Low,39.96,DIĞER_ODA + KAHVALTI_LOW,C
24,Girne,Oda + Kahvaltı,Low,40.04,GIRNE_ODA + KAHVALTI_LOW,C
23,Diğer,Yarım Pansiyon,Low,42.95,DIĞER_YARIM PANSIYON_LOW,C
22,Aydın,Oda + Kahvaltı,Low,44.45,AYDIN_ODA + KAHVALTI_LOW,C
21,Muğla,Yarım Pansiyon,High,45.82,MUĞLA_YARIM PANSIYON_HIGH,C
20,Muğla,Herşey Dahil,Low,48.30,MUĞLA_HERŞEY DAHIL_LOW,C
19,Girne,Yarım Pansiyon,Low,48.58,GIRNE_YARIM PANSIYON_LOW,C
18,İzmir,Oda + Kahvaltı,High,54.14,İZMIR_ODA + KAHVALTI_HIGH,C
17,Aydın,Herşey Dahil,High,54.95,AYDIN_HERŞEY DAHIL_HIGH,B
16,İzmir,Yarım Pansiyon,Low,55.35,İZMIR_YARIM PANSIYON_LOW,B
15,Girne,Yarım Pansiyon,High,58.38,GIRNE_YARIM PANSIYON_HIGH,B
14,Antalya,Oda + Kahvaltı,Low,60.67,ANTALYA_ODA + KAHVALTI_LOW,B
13,Muğla,Oda + Kahvaltı,High,61.26,MUĞLA_ODA + KAHVALTI_HIGH,B
12,Antalya,Herşey Dahil,Low,61.55,ANTALYA_HERŞEY DAHIL_LOW,B
11,Antalya,Yarım Pansiyon,Low,62.00,ANTALYA_YARIM PANSIYON_LOW,B
10,Muğla,Herşey Dahil,High,63.38,MUĞLA_HERŞEY DAHIL_HIGH,B
9,Antalya,Herşey Dahil,High,64.92,ANTALYA_HERŞEY DAHIL_HIGH,B
8,Antalya,Oda + Kahvaltı,High,66.27,ANTALYA_ODA + KAHVALTI_HIGH,A
7,Antalya,Yarım Pansiyon,High,73.26,ANTALYA_YARIM PANSIYON_HIGH,A
6,İzmir,Herşey Dahil,Low,74.31,İZMIR_HERŞEY DAHIL_LOW,A
5,İzmir,Herşey Dahil,High,74.75,İZMIR_HERŞEY DAHIL_HIGH,A
4,Diğer,Herşey Dahil,High,83.79,DIĞER_HERŞEY DAHIL_HIGH,A
3,Diğer,Herşey Dahil,Low,87.31,DIĞER_HERŞEY DAHIL_LOW,A
2,İzmir,Yarım Pansiyon,High,87.66,İZMIR_YARIM PANSIYON_HIGH,A
1,Girne,Herşey Dahil,Low,90.94,GIRNE_HERŞEY DAHIL_LOW,A
0,Girne,Herşey Dahil,High,103.94,GIRNE_HERŞEY DAHIL_HIGH,A

In [34]:
# In which segment is "ANTALYA_HERŞEY DAHIL_HIGH" and how much is expected?
new_user = "ANTALYA_HERŞEY DAHIL_HIGH"
agg_df[agg_df["sales_level_based"] == new_user]

  SaleCityName   ConceptName Seasons  Price          sales_level_based SEGMENT
9      Antalya  Herşey Dahil    High  64.92  ANTALYA_HERŞEY DAHIL_HIGH       B